// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: src/proto/notification.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";

export const protobufPackage = "notification";

export interface Recipient {
  userId: string;
  phoneNumber: string;
  email: string;
}

export interface NotificationContent {
  title: string;
  body: string;
}

export interface SendNotificationRequest {
  /** SMS/EMAIL/PUSH/IN_APP/WEBHOOK */
  type: string;
  recipient?: Recipient | undefined;
  content?: NotificationContent | undefined;
}

export interface SendNotificationResponse {
  id: string;
  success: boolean;
}

export interface SendBatchRequest {
  type: string;
  notifications: SendNotificationRequest[];
}

export interface SendBatchResponse {
  successCount: number;
  failedCount: number;
}

export interface CreateTemplateRequest {
  name: string;
  type: string;
  subject: string;
  content: string;
  variables: string[];
}

export interface UpdateTemplateRequest {
  id: string;
  name: string;
  subject: string;
  content: string;
  variables: string[];
}

export interface GetTemplateRequest {
  id: string;
}

export interface ListTemplatesRequest {
  type?: string | undefined;
}

export interface TemplateResponse {
  id: string;
  name: string;
  type: string;
  subject: string;
  content: string;
  variables: string[];
}

export interface ListTemplatesResponse {
  templates: TemplateResponse[];
}

export interface CallbackStatusRequest {
  id: string;
  status: string;
  messageId: string;
}

export interface CallbackStatusResponse {
  success: boolean;
}

function createBaseRecipient(): Recipient {
  return { userId: "", phoneNumber: "", email: "" };
}

export const Recipient: MessageFns<Recipient> = {
  encode(message: Recipient, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.userId !== "") {
      writer.uint32(10).string(message.userId);
    }
    if (message.phoneNumber !== "") {
      writer.uint32(18).string(message.phoneNumber);
    }
    if (message.email !== "") {
      writer.uint32(26).string(message.email);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): Recipient {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseRecipient();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.userId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.phoneNumber = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.email = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): Recipient {
    return {
      userId: isSet(object.userId) ? globalThis.String(object.userId) : "",
      phoneNumber: isSet(object.phoneNumber) ? globalThis.String(object.phoneNumber) : "",
      email: isSet(object.email) ? globalThis.String(object.email) : "",
    };
  },

  toJSON(message: Recipient): unknown {
    const obj: any = {};
    if (message.userId !== "") {
      obj.userId = message.userId;
    }
    if (message.phoneNumber !== "") {
      obj.phoneNumber = message.phoneNumber;
    }
    if (message.email !== "") {
      obj.email = message.email;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<Recipient>, I>>(base?: I): Recipient {
    return Recipient.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<Recipient>, I>>(object: I): Recipient {
    const message = createBaseRecipient();
    message.userId = object.userId ?? "";
    message.phoneNumber = object.phoneNumber ?? "";
    message.email = object.email ?? "";
    return message;
  },
};

function createBaseNotificationContent(): NotificationContent {
  return { title: "", body: "" };
}

export const NotificationContent: MessageFns<NotificationContent> = {
  encode(message: NotificationContent, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.title !== "") {
      writer.uint32(10).string(message.title);
    }
    if (message.body !== "") {
      writer.uint32(18).string(message.body);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NotificationContent {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNotificationContent();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.title = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.body = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NotificationContent {
    return {
      title: isSet(object.title) ? globalThis.String(object.title) : "",
      body: isSet(object.body) ? globalThis.String(object.body) : "",
    };
  },

  toJSON(message: NotificationContent): unknown {
    const obj: any = {};
    if (message.title !== "") {
      obj.title = message.title;
    }
    if (message.body !== "") {
      obj.body = message.body;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NotificationContent>, I>>(base?: I): NotificationContent {
    return NotificationContent.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NotificationContent>, I>>(object: I): NotificationContent {
    const message = createBaseNotificationContent();
    message.title = object.title ?? "";
    message.body = object.body ?? "";
    return message;
  },
};

function createBaseSendNotificationRequest(): SendNotificationRequest {
  return { type: "", recipient: undefined, content: undefined };
}

export const SendNotificationRequest: MessageFns<SendNotificationRequest> = {
  encode(message: SendNotificationRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    if (message.recipient !== undefined) {
      Recipient.encode(message.recipient, writer.uint32(18).fork()).join();
    }
    if (message.content !== undefined) {
      NotificationContent.encode(message.content, writer.uint32(26).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendNotificationRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendNotificationRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.recipient = Recipient.decode(reader, reader.uint32());
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.content = NotificationContent.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendNotificationRequest {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      recipient: isSet(object.recipient) ? Recipient.fromJSON(object.recipient) : undefined,
      content: isSet(object.content) ? NotificationContent.fromJSON(object.content) : undefined,
    };
  },

  toJSON(message: SendNotificationRequest): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.recipient !== undefined) {
      obj.recipient = Recipient.toJSON(message.recipient);
    }
    if (message.content !== undefined) {
      obj.content = NotificationContent.toJSON(message.content);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendNotificationRequest>, I>>(base?: I): SendNotificationRequest {
    return SendNotificationRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendNotificationRequest>, I>>(object: I): SendNotificationRequest {
    const message = createBaseSendNotificationRequest();
    message.type = object.type ?? "";
    message.recipient = (object.recipient !== undefined && object.recipient !== null)
      ? Recipient.fromPartial(object.recipient)
      : undefined;
    message.content = (object.content !== undefined && object.content !== null)
      ? NotificationContent.fromPartial(object.content)
      : undefined;
    return message;
  },
};

function createBaseSendNotificationResponse(): SendNotificationResponse {
  return { id: "", success: false };
}

export const SendNotificationResponse: MessageFns<SendNotificationResponse> = {
  encode(message: SendNotificationResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.success !== false) {
      writer.uint32(16).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendNotificationResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendNotificationResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendNotificationResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      success: isSet(object.success) ? globalThis.Boolean(object.success) : false,
    };
  },

  toJSON(message: SendNotificationResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendNotificationResponse>, I>>(base?: I): SendNotificationResponse {
    return SendNotificationResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendNotificationResponse>, I>>(object: I): SendNotificationResponse {
    const message = createBaseSendNotificationResponse();
    message.id = object.id ?? "";
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseSendBatchRequest(): SendBatchRequest {
  return { type: "", notifications: [] };
}

export const SendBatchRequest: MessageFns<SendBatchRequest> = {
  encode(message: SendBatchRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== "") {
      writer.uint32(10).string(message.type);
    }
    for (const v of message.notifications) {
      SendNotificationRequest.encode(v!, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendBatchRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendBatchRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.notifications.push(SendNotificationRequest.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendBatchRequest {
    return {
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      notifications: globalThis.Array.isArray(object?.notifications)
        ? object.notifications.map((e: any) => SendNotificationRequest.fromJSON(e))
        : [],
    };
  },

  toJSON(message: SendBatchRequest): unknown {
    const obj: any = {};
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.notifications?.length) {
      obj.notifications = message.notifications.map((e) => SendNotificationRequest.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendBatchRequest>, I>>(base?: I): SendBatchRequest {
    return SendBatchRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendBatchRequest>, I>>(object: I): SendBatchRequest {
    const message = createBaseSendBatchRequest();
    message.type = object.type ?? "";
    message.notifications = object.notifications?.map((e) => SendNotificationRequest.fromPartial(e)) || [];
    return message;
  },
};

function createBaseSendBatchResponse(): SendBatchResponse {
  return { successCount: 0, failedCount: 0 };
}

export const SendBatchResponse: MessageFns<SendBatchResponse> = {
  encode(message: SendBatchResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.successCount !== 0) {
      writer.uint32(8).int32(message.successCount);
    }
    if (message.failedCount !== 0) {
      writer.uint32(16).int32(message.failedCount);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): SendBatchResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseSendBatchResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.successCount = reader.int32();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.failedCount = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): SendBatchResponse {
    return {
      successCount: isSet(object.successCount) ? globalThis.Number(object.successCount) : 0,
      failedCount: isSet(object.failedCount) ? globalThis.Number(object.failedCount) : 0,
    };
  },

  toJSON(message: SendBatchResponse): unknown {
    const obj: any = {};
    if (message.successCount !== 0) {
      obj.successCount = Math.round(message.successCount);
    }
    if (message.failedCount !== 0) {
      obj.failedCount = Math.round(message.failedCount);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<SendBatchResponse>, I>>(base?: I): SendBatchResponse {
    return SendBatchResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<SendBatchResponse>, I>>(object: I): SendBatchResponse {
    const message = createBaseSendBatchResponse();
    message.successCount = object.successCount ?? 0;
    message.failedCount = object.failedCount ?? 0;
    return message;
  },
};

function createBaseCreateTemplateRequest(): CreateTemplateRequest {
  return { name: "", type: "", subject: "", content: "", variables: [] };
}

export const CreateTemplateRequest: MessageFns<CreateTemplateRequest> = {
  encode(message: CreateTemplateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.name !== "") {
      writer.uint32(10).string(message.name);
    }
    if (message.type !== "") {
      writer.uint32(18).string(message.type);
    }
    if (message.subject !== "") {
      writer.uint32(26).string(message.subject);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    for (const v of message.variables) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CreateTemplateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCreateTemplateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.variables.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CreateTemplateRequest {
    return {
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      subject: isSet(object.subject) ? globalThis.String(object.subject) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      variables: globalThis.Array.isArray(object?.variables)
        ? object.variables.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: CreateTemplateRequest): unknown {
    const obj: any = {};
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.subject !== "") {
      obj.subject = message.subject;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.variables?.length) {
      obj.variables = message.variables;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CreateTemplateRequest>, I>>(base?: I): CreateTemplateRequest {
    return CreateTemplateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CreateTemplateRequest>, I>>(object: I): CreateTemplateRequest {
    const message = createBaseCreateTemplateRequest();
    message.name = object.name ?? "";
    message.type = object.type ?? "";
    message.subject = object.subject ?? "";
    message.content = object.content ?? "";
    message.variables = object.variables?.map((e) => e) || [];
    return message;
  },
};

function createBaseUpdateTemplateRequest(): UpdateTemplateRequest {
  return { id: "", name: "", subject: "", content: "", variables: [] };
}

export const UpdateTemplateRequest: MessageFns<UpdateTemplateRequest> = {
  encode(message: UpdateTemplateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.subject !== "") {
      writer.uint32(26).string(message.subject);
    }
    if (message.content !== "") {
      writer.uint32(34).string(message.content);
    }
    for (const v of message.variables) {
      writer.uint32(42).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): UpdateTemplateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseUpdateTemplateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.variables.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): UpdateTemplateRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      subject: isSet(object.subject) ? globalThis.String(object.subject) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      variables: globalThis.Array.isArray(object?.variables)
        ? object.variables.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: UpdateTemplateRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.subject !== "") {
      obj.subject = message.subject;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.variables?.length) {
      obj.variables = message.variables;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<UpdateTemplateRequest>, I>>(base?: I): UpdateTemplateRequest {
    return UpdateTemplateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<UpdateTemplateRequest>, I>>(object: I): UpdateTemplateRequest {
    const message = createBaseUpdateTemplateRequest();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.subject = object.subject ?? "";
    message.content = object.content ?? "";
    message.variables = object.variables?.map((e) => e) || [];
    return message;
  },
};

function createBaseGetTemplateRequest(): GetTemplateRequest {
  return { id: "" };
}

export const GetTemplateRequest: MessageFns<GetTemplateRequest> = {
  encode(message: GetTemplateRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): GetTemplateRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseGetTemplateRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): GetTemplateRequest {
    return { id: isSet(object.id) ? globalThis.String(object.id) : "" };
  },

  toJSON(message: GetTemplateRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<GetTemplateRequest>, I>>(base?: I): GetTemplateRequest {
    return GetTemplateRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<GetTemplateRequest>, I>>(object: I): GetTemplateRequest {
    const message = createBaseGetTemplateRequest();
    message.id = object.id ?? "";
    return message;
  },
};

function createBaseListTemplatesRequest(): ListTemplatesRequest {
  return { type: undefined };
}

export const ListTemplatesRequest: MessageFns<ListTemplatesRequest> = {
  encode(message: ListTemplatesRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.type !== undefined) {
      writer.uint32(10).string(message.type);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTemplatesRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTemplatesRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.type = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTemplatesRequest {
    return { type: isSet(object.type) ? globalThis.String(object.type) : undefined };
  },

  toJSON(message: ListTemplatesRequest): unknown {
    const obj: any = {};
    if (message.type !== undefined) {
      obj.type = message.type;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTemplatesRequest>, I>>(base?: I): ListTemplatesRequest {
    return ListTemplatesRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTemplatesRequest>, I>>(object: I): ListTemplatesRequest {
    const message = createBaseListTemplatesRequest();
    message.type = object.type ?? undefined;
    return message;
  },
};

function createBaseTemplateResponse(): TemplateResponse {
  return { id: "", name: "", type: "", subject: "", content: "", variables: [] };
}

export const TemplateResponse: MessageFns<TemplateResponse> = {
  encode(message: TemplateResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.name !== "") {
      writer.uint32(18).string(message.name);
    }
    if (message.type !== "") {
      writer.uint32(26).string(message.type);
    }
    if (message.subject !== "") {
      writer.uint32(34).string(message.subject);
    }
    if (message.content !== "") {
      writer.uint32(42).string(message.content);
    }
    for (const v of message.variables) {
      writer.uint32(50).string(v!);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TemplateResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTemplateResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.name = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.type = reader.string();
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.subject = reader.string();
          continue;
        }
        case 5: {
          if (tag !== 42) {
            break;
          }

          message.content = reader.string();
          continue;
        }
        case 6: {
          if (tag !== 50) {
            break;
          }

          message.variables.push(reader.string());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TemplateResponse {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      name: isSet(object.name) ? globalThis.String(object.name) : "",
      type: isSet(object.type) ? globalThis.String(object.type) : "",
      subject: isSet(object.subject) ? globalThis.String(object.subject) : "",
      content: isSet(object.content) ? globalThis.String(object.content) : "",
      variables: globalThis.Array.isArray(object?.variables)
        ? object.variables.map((e: any) => globalThis.String(e))
        : [],
    };
  },

  toJSON(message: TemplateResponse): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.name !== "") {
      obj.name = message.name;
    }
    if (message.type !== "") {
      obj.type = message.type;
    }
    if (message.subject !== "") {
      obj.subject = message.subject;
    }
    if (message.content !== "") {
      obj.content = message.content;
    }
    if (message.variables?.length) {
      obj.variables = message.variables;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TemplateResponse>, I>>(base?: I): TemplateResponse {
    return TemplateResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TemplateResponse>, I>>(object: I): TemplateResponse {
    const message = createBaseTemplateResponse();
    message.id = object.id ?? "";
    message.name = object.name ?? "";
    message.type = object.type ?? "";
    message.subject = object.subject ?? "";
    message.content = object.content ?? "";
    message.variables = object.variables?.map((e) => e) || [];
    return message;
  },
};

function createBaseListTemplatesResponse(): ListTemplatesResponse {
  return { templates: [] };
}

export const ListTemplatesResponse: MessageFns<ListTemplatesResponse> = {
  encode(message: ListTemplatesResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    for (const v of message.templates) {
      TemplateResponse.encode(v!, writer.uint32(10).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ListTemplatesResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseListTemplatesResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.templates.push(TemplateResponse.decode(reader, reader.uint32()));
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ListTemplatesResponse {
    return {
      templates: globalThis.Array.isArray(object?.templates)
        ? object.templates.map((e: any) => TemplateResponse.fromJSON(e))
        : [],
    };
  },

  toJSON(message: ListTemplatesResponse): unknown {
    const obj: any = {};
    if (message.templates?.length) {
      obj.templates = message.templates.map((e) => TemplateResponse.toJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ListTemplatesResponse>, I>>(base?: I): ListTemplatesResponse {
    return ListTemplatesResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ListTemplatesResponse>, I>>(object: I): ListTemplatesResponse {
    const message = createBaseListTemplatesResponse();
    message.templates = object.templates?.map((e) => TemplateResponse.fromPartial(e)) || [];
    return message;
  },
};

function createBaseCallbackStatusRequest(): CallbackStatusRequest {
  return { id: "", status: "", messageId: "" };
}

export const CallbackStatusRequest: MessageFns<CallbackStatusRequest> = {
  encode(message: CallbackStatusRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.id !== "") {
      writer.uint32(10).string(message.id);
    }
    if (message.status !== "") {
      writer.uint32(18).string(message.status);
    }
    if (message.messageId !== "") {
      writer.uint32(26).string(message.messageId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallbackStatusRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallbackStatusRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.id = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.status = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.messageId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallbackStatusRequest {
    return {
      id: isSet(object.id) ? globalThis.String(object.id) : "",
      status: isSet(object.status) ? globalThis.String(object.status) : "",
      messageId: isSet(object.messageId) ? globalThis.String(object.messageId) : "",
    };
  },

  toJSON(message: CallbackStatusRequest): unknown {
    const obj: any = {};
    if (message.id !== "") {
      obj.id = message.id;
    }
    if (message.status !== "") {
      obj.status = message.status;
    }
    if (message.messageId !== "") {
      obj.messageId = message.messageId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallbackStatusRequest>, I>>(base?: I): CallbackStatusRequest {
    return CallbackStatusRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallbackStatusRequest>, I>>(object: I): CallbackStatusRequest {
    const message = createBaseCallbackStatusRequest();
    message.id = object.id ?? "";
    message.status = object.status ?? "";
    message.messageId = object.messageId ?? "";
    return message;
  },
};

function createBaseCallbackStatusResponse(): CallbackStatusResponse {
  return { success: false };
}

export const CallbackStatusResponse: MessageFns<CallbackStatusResponse> = {
  encode(message: CallbackStatusResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): CallbackStatusResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseCallbackStatusResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): CallbackStatusResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: CallbackStatusResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<CallbackStatusResponse>, I>>(base?: I): CallbackStatusResponse {
    return CallbackStatusResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<CallbackStatusResponse>, I>>(object: I): CallbackStatusResponse {
    const message = createBaseCallbackStatusResponse();
    message.success = object.success ?? false;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
