// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: src/proto/queue.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import {
  type CallOptions,
  type ChannelCredentials,
  Client,
  type ClientOptions,
  type ClientReadableStream,
  type ClientUnaryCall,
  type handleServerStreamingCall,
  type handleUnaryCall,
  makeGenericClientConstructor,
  type Metadata,
  type ServiceError,
  type UntypedServiceImplementation,
} from "@grpc/grpc-js";

export interface PublishTaskRequest {
  queue: string;
  payload: string;
  priority: number;
  delayMs: number;
}

export interface PublishTaskResponse {
  taskId: string;
}

export interface AckRequest {
  taskId: string;
}

export interface AckResponse {
  success: boolean;
}

export interface NackRequest {
  taskId: string;
  reason: string;
}

export interface NackResponse {
  success: boolean;
}

export interface ConsumeRequest {
  queue: string;
  maxInFlight: number;
}

export interface TaskMessage {
  taskId: string;
  payload: string;
  priority: number;
}

function createBasePublishTaskRequest(): PublishTaskRequest {
  return { queue: "", payload: "", priority: 0, delayMs: 0 };
}

export const PublishTaskRequest: MessageFns<PublishTaskRequest> = {
  encode(message: PublishTaskRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queue !== "") {
      writer.uint32(10).string(message.queue);
    }
    if (message.payload !== "") {
      writer.uint32(18).string(message.payload);
    }
    if (message.priority !== 0) {
      writer.uint32(24).int32(message.priority);
    }
    if (message.delayMs !== 0) {
      writer.uint32(32).int64(message.delayMs);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublishTaskRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishTaskRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.queue = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.priority = reader.int32();
          continue;
        }
        case 4: {
          if (tag !== 32) {
            break;
          }

          message.delayMs = longToNumber(reader.int64());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PublishTaskRequest {
    return {
      queue: isSet(object.queue) ? globalThis.String(object.queue) : "",
      payload: isSet(object.payload) ? globalThis.String(object.payload) : "",
      priority: isSet(object.priority) ? globalThis.Number(object.priority) : 0,
      delayMs: isSet(object.delayMs) ? globalThis.Number(object.delayMs) : 0,
    };
  },

  toJSON(message: PublishTaskRequest): unknown {
    const obj: any = {};
    if (message.queue !== "") {
      obj.queue = message.queue;
    }
    if (message.payload !== "") {
      obj.payload = message.payload;
    }
    if (message.priority !== 0) {
      obj.priority = Math.round(message.priority);
    }
    if (message.delayMs !== 0) {
      obj.delayMs = Math.round(message.delayMs);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PublishTaskRequest>, I>>(base?: I): PublishTaskRequest {
    return PublishTaskRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PublishTaskRequest>, I>>(object: I): PublishTaskRequest {
    const message = createBasePublishTaskRequest();
    message.queue = object.queue ?? "";
    message.payload = object.payload ?? "";
    message.priority = object.priority ?? 0;
    message.delayMs = object.delayMs ?? 0;
    return message;
  },
};

function createBasePublishTaskResponse(): PublishTaskResponse {
  return { taskId: "" };
}

export const PublishTaskResponse: MessageFns<PublishTaskResponse> = {
  encode(message: PublishTaskResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): PublishTaskResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBasePublishTaskResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): PublishTaskResponse {
    return { taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "" };
  },

  toJSON(message: PublishTaskResponse): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<PublishTaskResponse>, I>>(base?: I): PublishTaskResponse {
    return PublishTaskResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<PublishTaskResponse>, I>>(object: I): PublishTaskResponse {
    const message = createBasePublishTaskResponse();
    message.taskId = object.taskId ?? "";
    return message;
  },
};

function createBaseAckRequest(): AckRequest {
  return { taskId: "" };
}

export const AckRequest: MessageFns<AckRequest> = {
  encode(message: AckRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AckRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAckRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AckRequest {
    return { taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "" };
  },

  toJSON(message: AckRequest): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AckRequest>, I>>(base?: I): AckRequest {
    return AckRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AckRequest>, I>>(object: I): AckRequest {
    const message = createBaseAckRequest();
    message.taskId = object.taskId ?? "";
    return message;
  },
};

function createBaseAckResponse(): AckResponse {
  return { success: false };
}

export const AckResponse: MessageFns<AckResponse> = {
  encode(message: AckResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): AckResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseAckResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): AckResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: AckResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<AckResponse>, I>>(base?: I): AckResponse {
    return AckResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<AckResponse>, I>>(object: I): AckResponse {
    const message = createBaseAckResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseNackRequest(): NackRequest {
  return { taskId: "", reason: "" };
}

export const NackRequest: MessageFns<NackRequest> = {
  encode(message: NackRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.reason !== "") {
      writer.uint32(18).string(message.reason);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NackRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNackRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.reason = reader.string();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NackRequest {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "",
      reason: isSet(object.reason) ? globalThis.String(object.reason) : "",
    };
  },

  toJSON(message: NackRequest): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.reason !== "") {
      obj.reason = message.reason;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NackRequest>, I>>(base?: I): NackRequest {
    return NackRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NackRequest>, I>>(object: I): NackRequest {
    const message = createBaseNackRequest();
    message.taskId = object.taskId ?? "";
    message.reason = object.reason ?? "";
    return message;
  },
};

function createBaseNackResponse(): NackResponse {
  return { success: false };
}

export const NackResponse: MessageFns<NackResponse> = {
  encode(message: NackResponse, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.success !== false) {
      writer.uint32(8).bool(message.success);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): NackResponse {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseNackResponse();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.success = reader.bool();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): NackResponse {
    return { success: isSet(object.success) ? globalThis.Boolean(object.success) : false };
  },

  toJSON(message: NackResponse): unknown {
    const obj: any = {};
    if (message.success !== false) {
      obj.success = message.success;
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<NackResponse>, I>>(base?: I): NackResponse {
    return NackResponse.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<NackResponse>, I>>(object: I): NackResponse {
    const message = createBaseNackResponse();
    message.success = object.success ?? false;
    return message;
  },
};

function createBaseConsumeRequest(): ConsumeRequest {
  return { queue: "", maxInFlight: 0 };
}

export const ConsumeRequest: MessageFns<ConsumeRequest> = {
  encode(message: ConsumeRequest, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.queue !== "") {
      writer.uint32(10).string(message.queue);
    }
    if (message.maxInFlight !== 0) {
      writer.uint32(16).int32(message.maxInFlight);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): ConsumeRequest {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseConsumeRequest();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.queue = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 16) {
            break;
          }

          message.maxInFlight = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): ConsumeRequest {
    return {
      queue: isSet(object.queue) ? globalThis.String(object.queue) : "",
      maxInFlight: isSet(object.maxInFlight) ? globalThis.Number(object.maxInFlight) : 0,
    };
  },

  toJSON(message: ConsumeRequest): unknown {
    const obj: any = {};
    if (message.queue !== "") {
      obj.queue = message.queue;
    }
    if (message.maxInFlight !== 0) {
      obj.maxInFlight = Math.round(message.maxInFlight);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<ConsumeRequest>, I>>(base?: I): ConsumeRequest {
    return ConsumeRequest.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<ConsumeRequest>, I>>(object: I): ConsumeRequest {
    const message = createBaseConsumeRequest();
    message.queue = object.queue ?? "";
    message.maxInFlight = object.maxInFlight ?? 0;
    return message;
  },
};

function createBaseTaskMessage(): TaskMessage {
  return { taskId: "", payload: "", priority: 0 };
}

export const TaskMessage: MessageFns<TaskMessage> = {
  encode(message: TaskMessage, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.taskId !== "") {
      writer.uint32(10).string(message.taskId);
    }
    if (message.payload !== "") {
      writer.uint32(18).string(message.payload);
    }
    if (message.priority !== 0) {
      writer.uint32(24).int32(message.priority);
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): TaskMessage {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseTaskMessage();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.taskId = reader.string();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.payload = reader.string();
          continue;
        }
        case 3: {
          if (tag !== 24) {
            break;
          }

          message.priority = reader.int32();
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): TaskMessage {
    return {
      taskId: isSet(object.taskId) ? globalThis.String(object.taskId) : "",
      payload: isSet(object.payload) ? globalThis.String(object.payload) : "",
      priority: isSet(object.priority) ? globalThis.Number(object.priority) : 0,
    };
  },

  toJSON(message: TaskMessage): unknown {
    const obj: any = {};
    if (message.taskId !== "") {
      obj.taskId = message.taskId;
    }
    if (message.payload !== "") {
      obj.payload = message.payload;
    }
    if (message.priority !== 0) {
      obj.priority = Math.round(message.priority);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<TaskMessage>, I>>(base?: I): TaskMessage {
    return TaskMessage.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<TaskMessage>, I>>(object: I): TaskMessage {
    const message = createBaseTaskMessage();
    message.taskId = object.taskId ?? "";
    message.payload = object.payload ?? "";
    message.priority = object.priority ?? 0;
    return message;
  },
};

export type QueueServiceService = typeof QueueServiceService;
export const QueueServiceService = {
  publishTask: {
    path: "/queue.QueueService/PublishTask" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: PublishTaskRequest): Buffer => Buffer.from(PublishTaskRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): PublishTaskRequest => PublishTaskRequest.decode(value),
    responseSerialize: (value: PublishTaskResponse): Buffer => Buffer.from(PublishTaskResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): PublishTaskResponse => PublishTaskResponse.decode(value),
  },
  ack: {
    path: "/queue.QueueService/Ack" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: AckRequest): Buffer => Buffer.from(AckRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): AckRequest => AckRequest.decode(value),
    responseSerialize: (value: AckResponse): Buffer => Buffer.from(AckResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): AckResponse => AckResponse.decode(value),
  },
  nack: {
    path: "/queue.QueueService/Nack" as const,
    requestStream: false as const,
    responseStream: false as const,
    requestSerialize: (value: NackRequest): Buffer => Buffer.from(NackRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): NackRequest => NackRequest.decode(value),
    responseSerialize: (value: NackResponse): Buffer => Buffer.from(NackResponse.encode(value).finish()),
    responseDeserialize: (value: Buffer): NackResponse => NackResponse.decode(value),
  },
  consume: {
    path: "/queue.QueueService/Consume" as const,
    requestStream: false as const,
    responseStream: true as const,
    requestSerialize: (value: ConsumeRequest): Buffer => Buffer.from(ConsumeRequest.encode(value).finish()),
    requestDeserialize: (value: Buffer): ConsumeRequest => ConsumeRequest.decode(value),
    responseSerialize: (value: TaskMessage): Buffer => Buffer.from(TaskMessage.encode(value).finish()),
    responseDeserialize: (value: Buffer): TaskMessage => TaskMessage.decode(value),
  },
} as const;

export interface QueueServiceServer extends UntypedServiceImplementation {
  publishTask: handleUnaryCall<PublishTaskRequest, PublishTaskResponse>;
  ack: handleUnaryCall<AckRequest, AckResponse>;
  nack: handleUnaryCall<NackRequest, NackResponse>;
  consume: handleServerStreamingCall<ConsumeRequest, TaskMessage>;
}

export interface QueueServiceClient extends Client {
  publishTask(
    request: PublishTaskRequest,
    callback: (error: ServiceError | null, response: PublishTaskResponse) => void,
  ): ClientUnaryCall;
  publishTask(
    request: PublishTaskRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: PublishTaskResponse) => void,
  ): ClientUnaryCall;
  publishTask(
    request: PublishTaskRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: PublishTaskResponse) => void,
  ): ClientUnaryCall;
  ack(request: AckRequest, callback: (error: ServiceError | null, response: AckResponse) => void): ClientUnaryCall;
  ack(
    request: AckRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: AckResponse) => void,
  ): ClientUnaryCall;
  ack(
    request: AckRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: AckResponse) => void,
  ): ClientUnaryCall;
  nack(request: NackRequest, callback: (error: ServiceError | null, response: NackResponse) => void): ClientUnaryCall;
  nack(
    request: NackRequest,
    metadata: Metadata,
    callback: (error: ServiceError | null, response: NackResponse) => void,
  ): ClientUnaryCall;
  nack(
    request: NackRequest,
    metadata: Metadata,
    options: Partial<CallOptions>,
    callback: (error: ServiceError | null, response: NackResponse) => void,
  ): ClientUnaryCall;
  consume(request: ConsumeRequest, options?: Partial<CallOptions>): ClientReadableStream<TaskMessage>;
  consume(
    request: ConsumeRequest,
    metadata?: Metadata,
    options?: Partial<CallOptions>,
  ): ClientReadableStream<TaskMessage>;
}

export const QueueServiceClient = makeGenericClientConstructor(
  QueueServiceService,
  "queue.QueueService",
) as unknown as {
  new (address: string, credentials: ChannelCredentials, options?: Partial<ClientOptions>): QueueServiceClient;
  service: typeof QueueServiceService;
  serviceName: string;
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function longToNumber(int64: { toString(): string }): number {
  const num = globalThis.Number(int64.toString());
  if (num > globalThis.Number.MAX_SAFE_INTEGER) {
    throw new globalThis.Error("Value is larger than Number.MAX_SAFE_INTEGER");
  }
  if (num < globalThis.Number.MIN_SAFE_INTEGER) {
    throw new globalThis.Error("Value is smaller than Number.MIN_SAFE_INTEGER");
  }
  return num;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
