// Generated by ts-proto v1.0.0
// DO NOT EDIT

import * as grpc from '@grpc/grpc-js';

export interface CreateOrderRequest {
  userId: number;
  addressId: number;
  expectPickupTime: string;
  channel: string;
  remark: string;
  items: OrderItemInput[];
}

export interface OrderItemInput {
  categoryId: number;
  estimatedWeight: string;
  unitPrice: string;
}

export interface GetOrderRequest {
  id: number;
}

export interface UpdateOrderStatusRequest {
  id: number;
  status: string;
}

export interface CancelOrderRequest {
  id: number;
  reason: string;
}

export interface AssignOrderRequest {
  orderId: number;
  courierId: number;
}

export interface UpdateAssignmentStatusRequest {
  assignmentId: number;
  status: string;
}

export interface GetUserStatisticsRequest {
  userId: number;
}

export interface UserStatisticsResponse {
  totalOrders: number;
  totalAmount: number;
  savedCarbon: number;
}

export interface OrderResponse {
  id: number;
  orderNo: string;
  userId: number;
  addressId: number;
  status: string;
  expectPickupTime: string;
  actualPickupTime: string;
  estimatedAmount: string;
  settlementAmount: string;
  payAmount: string;
  channel: string;
  remark: string;
  createdAt: string;
  updatedAt: string;
  items: OrderItemResponse[];
  assignments: AssignmentResponse[];
}

export interface OrderItemResponse {
  id: number;
  categoryId: number;
  estimatedWeight: string;
  actualWeight: string;
  unitPrice: string;
  amount: string;
}

export interface AssignmentResponse {
  id: number;
  courierId: number;
  status: string;
  acceptedAt: string;
  arrivedAt: string;
  finishedAt: string;
  createdAt: string;
}

export interface OrderServiceHandlers extends grpc.UntypedServiceImplementation {
  createOrder: grpc.handleUnaryCall<CreateOrderRequest, OrderResponse>;
  getOrder: grpc.handleUnaryCall<GetOrderRequest, OrderResponse>;
  updateOrderStatus: grpc.handleUnaryCall<UpdateOrderStatusRequest, OrderResponse>;
  cancelOrder: grpc.handleUnaryCall<CancelOrderRequest, OrderResponse>;
  assignOrder: grpc.handleUnaryCall<AssignOrderRequest, AssignmentResponse>;
  updateAssignmentStatus: grpc.handleUnaryCall<UpdateAssignmentStatusRequest, AssignmentResponse>;
  getUserStatistics: grpc.handleUnaryCall<GetUserStatisticsRequest, UserStatisticsResponse>;
}

export const OrderServiceService: grpc.ServiceDefinition<OrderServiceHandlers> = {
  createOrder: {
    path: '/OrderService/CreateOrder',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CreateOrderRequest) => Buffer.from(JSON.stringify(value)),
    requestDeserialize: (value: Buffer) => JSON.parse(value.toString()),
    responseSerialize: (value: OrderResponse) => Buffer.from(JSON.stringify(value)),
    responseDeserialize: (value: Buffer) => JSON.parse(value.toString()),
  },
  getOrder: {
    path: '/OrderService/GetOrder',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetOrderRequest) => Buffer.from(JSON.stringify(value)),
    requestDeserialize: (value: Buffer) => JSON.parse(value.toString()),
    responseSerialize: (value: OrderResponse) => Buffer.from(JSON.stringify(value)),
    responseDeserialize: (value: Buffer) => JSON.parse(value.toString()),
  },
  updateOrderStatus: {
    path: '/OrderService/UpdateOrderStatus',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateOrderStatusRequest) => Buffer.from(JSON.stringify(value)),
    requestDeserialize: (value: Buffer) => JSON.parse(value.toString()),
    responseSerialize: (value: OrderResponse) => Buffer.from(JSON.stringify(value)),
    responseDeserialize: (value: Buffer) => JSON.parse(value.toString()),
  },
  cancelOrder: {
    path: '/OrderService/CancelOrder',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: CancelOrderRequest) => Buffer.from(JSON.stringify(value)),
    requestDeserialize: (value: Buffer) => JSON.parse(value.toString()),
    responseSerialize: (value: OrderResponse) => Buffer.from(JSON.stringify(value)),
    responseDeserialize: (value: Buffer) => JSON.parse(value.toString()),
  },
  assignOrder: {
    path: '/OrderService/AssignOrder',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: AssignOrderRequest) => Buffer.from(JSON.stringify(value)),
    requestDeserialize: (value: Buffer) => JSON.parse(value.toString()),
    responseSerialize: (value: AssignmentResponse) => Buffer.from(JSON.stringify(value)),
    responseDeserialize: (value: Buffer) => JSON.parse(value.toString()),
  },
  updateAssignmentStatus: {
    path: '/OrderService/UpdateAssignmentStatus',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: UpdateAssignmentStatusRequest) => Buffer.from(JSON.stringify(value)),
    requestDeserialize: (value: Buffer) => JSON.parse(value.toString()),
    responseSerialize: (value: AssignmentResponse) => Buffer.from(JSON.stringify(value)),
    responseDeserialize: (value: Buffer) => JSON.parse(value.toString()),
  },
  getUserStatistics: {
    path: '/OrderService/GetUserStatistics',
    requestStream: false,
    responseStream: false,
    requestSerialize: (value: GetUserStatisticsRequest) => Buffer.from(JSON.stringify(value)),
    requestDeserialize: (value: Buffer) => JSON.parse(value.toString()),
    responseSerialize: (value: UserStatisticsResponse) => Buffer.from(JSON.stringify(value)),
    responseDeserialize: (value: Buffer) => JSON.parse(value.toString()),
  },
};