// Generated by ts-proto v1.0.0
// DO NOT EDIT

import * as grpc from '@grpc/grpc-js';

export interface CreatePaymentRequest {
  orderId: number;
  total: string;
  provider: string;
}

export interface GetPaymentRequest {
  id: number;
}

export interface PaymentNotifyRequest {
  outTradeNo: string;
  transactionId: string;
  totalFee: string;
  tradeState: string;
  notifyRaw: string;
}

export interface CreateRefundRequest {
  paymentId: string;
  refundAmount: string;
  reason: string;
}

export interface RefundNotifyRequest {
  outRefundNo: string;
  refundStatus: string;
  successTime: string;
  notifyRaw: string;
}

export interface PaymentResponse {
  id: string;
  outTradeNo: string;
  transactionId: string;
  total: string;
  status: string;
  provider: string;
  createdAt: string;
  updatedAt: string;
}

export interface RefundResponse {
  id: string;
  outRefundNo: string;
  refundAmount: string;
  status: string;
  reason: string;
  createdAt: string;
  updatedAt: string;
}

// 支付日志相关接口
export interface CreatePaymentLogRequest {
  orderId: string;
  transactionId: string;
  status: string;
  amount: string;
  provider: string;
  reason: string;
}

export interface GetPaymentLogsByOrderIdRequest {
  orderId: string;
}

export interface GetPaymentLogByTransactionIdRequest {
  transactionId: string;
}

export interface IsTransactionProcessedRequest {
  transactionId: string;
}

export interface GetPaymentStatsRequest {
  startDate: string;
  endDate: string;
}

export interface PaymentLogResponse {
  id: string;
  orderId: string;
  transactionId: string;
  status: string;
  amount: string;
  provider: string;
  reason: string;
  createdAt: string;
  updatedAt: string;
}

export interface PaymentLogsResponse {
  logs: PaymentLogResponse[];
}

export interface IsTransactionProcessedResponse {
  processed: boolean;
}

export interface PaymentStatsResponse {
  total: number;
  success: number;
  failed: number;
  closed: number;
  totalAmount: string;
}

export interface PaymentServiceHandlers extends grpc.UntypedServiceImplementation {
  createPayment: grpc.handleUnaryCall<CreatePaymentRequest, PaymentResponse>;
  getPayment: grpc.handleUnaryCall<GetPaymentRequest, PaymentResponse>;
  handlePaymentNotify: grpc.handleUnaryCall<PaymentNotifyRequest, PaymentResponse>;
  createRefund: grpc.handleUnaryCall<CreateRefundRequest, RefundResponse>;
  handleRefundNotify: grpc.handleUnaryCall<RefundNotifyRequest, RefundResponse>;
  createPaymentLog: grpc.handleUnaryCall<CreatePaymentLogRequest, PaymentLogResponse>;
  getPaymentLogsByOrderId: grpc.handleUnaryCall<GetPaymentLogsByOrderIdRequest, PaymentLogsResponse>;
  getPaymentLogByTransactionId: grpc.handleUnaryCall<GetPaymentLogByTransactionIdRequest, PaymentLogResponse>;
  isTransactionProcessed: grpc.handleUnaryCall<IsTransactionProcessedRequest, IsTransactionProcessedResponse>;
  getPaymentStats: grpc.handleUnaryCall<GetPaymentStatsRequest, PaymentStatsResponse>;
}

export const PaymentServiceService: grpc.ServiceDefinition<PaymentServiceHandlers> = {} as any;