// Generated by ts-proto v1.0.0
// DO NOT EDIT

import * as grpc from '@grpc/grpc-js';

export interface CreatePaymentRequest {
  orderId: number;
  total: string;
  provider: string;
}

export interface GetPaymentRequest {
  id: number;
}

export interface PaymentNotifyRequest {
  outTradeNo: string;
  transactionId: string;
  totalFee: string;
  tradeState: string;
  notifyRaw: string;
}

export interface CreateRefundRequest {
  paymentId: string;
  refundAmount: string;
  reason: string;
}

export interface RefundNotifyRequest {
  outRefundNo: string;
  refundStatus: string;
  successTime: string;
  notifyRaw: string;
}

export interface PaymentResponse {
  id: string;
  outTradeNo: string;
  transactionId: string;
  total: string;
  status: string;
  provider: string;
  createdAt: string;
  updatedAt: string;
}

export interface RefundResponse {
  id: string;
  outRefundNo: string;
  refundAmount: string;
  status: string;
  reason: string;
  createdAt: string;
  updatedAt: string;
}

export interface PaymentServiceHandlers extends grpc.UntypedServiceImplementation {
  createPayment: grpc.handleUnaryCall<CreatePaymentRequest, PaymentResponse>;
  getPayment: grpc.handleUnaryCall<GetPaymentRequest, PaymentResponse>;
  handlePaymentNotify: grpc.handleUnaryCall<PaymentNotifyRequest, PaymentResponse>;
  createRefund: grpc.handleUnaryCall<CreateRefundRequest, RefundResponse>;
  handleRefundNotify: grpc.handleUnaryCall<RefundNotifyRequest, RefundResponse>;
}

export const PaymentServiceService: grpc.ServiceDefinition<PaymentServiceHandlers> = {} as any;