syntax = "proto3";

package payment;

service PaymentService {
  rpc Create(CreatePaymentRequest) returns (PaymentResponse) {}
  rpc FindOne(FindOneRequest) returns (PaymentResponse) {}
  rpc FindByOrderId(FindByOrderIdRequest) returns (PaymentListResponse) {}
  rpc UpdateStatus(UpdateStatusRequest) returns (PaymentResponse) {}
  rpc CreateRefund(CreateRefundRequest) returns (RefundResponse) {}
  rpc UpdateRefundStatus(UpdateRefundStatusRequest) returns (RefundResponse) {}
}

message FindOneRequest {
  int64 id = 1;
}

message FindByOrderIdRequest {
  int64 order_id = 1;
}

message CreatePaymentRequest {
  int64 order_id = 1;
  string method = 2;
  double amount = 3;
  string provider = 4;
}

message UpdateStatusRequest {
  string transaction_id = 1;
  string status = 2;
}

message CreateRefundRequest {
  int64 payment_id = 1;
  double refund_amount = 2;
  string reason = 3;
}

message UpdateRefundStatusRequest {
  int64 refund_id = 1;
  string status = 2;
}

message PaymentResponse {
  int64 id = 1;
  int64 order_id = 2;
  string provider = 3;
  string out_trade_no = 4;
  string transaction_id = 5;
  double total = 6;
  string status = 7;
  string created_at = 8;
  string updated_at = 9;
  repeated RefundResponse refunds = 10;
}

message RefundResponse {
  int64 id = 1;
  int64 payment_id = 2;
  string out_refund_no = 3;
  double refund_amount = 4;
  string status = 5;
  string reason = 6;
  string created_at = 7;
  string updated_at = 8;
}

message PaymentListResponse {
  repeated PaymentResponse payments = 1;
}