// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: account.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "account";

export interface GetUserRequest {
  id: string;
}

export interface CreateUserRequest {
  mobile: string;
  nickname?: string | undefined;
  avatarUrl?: string | undefined;
}

export interface UpdateUserRequest {
  id: string;
  nickname?: string | undefined;
  avatarUrl?: string | undefined;
}

export interface UserResponse {
  id: string;
  mobile: string;
  nickname: string;
  avatarUrl: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface Empty {
}

export const ACCOUNT_PACKAGE_NAME = "account";

export interface AccountServiceClient {
  getUser(request: GetUserRequest, metadata?: Metadata): Observable<UserResponse>;

  createUser(request: CreateUserRequest, metadata?: Metadata): Observable<UserResponse>;

  updateUser(request: UpdateUserRequest, metadata?: Metadata): Observable<UserResponse>;
}

export interface AccountServiceController {
  getUser(
    request: GetUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  createUser(
    request: CreateUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateUser(
    request: UpdateUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function AccountServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getUser", "createUser", "updateUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AccountService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AccountService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ACCOUNT_SERVICE_NAME = "AccountService";
