// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: account.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "account";

export interface GetUserRequest {
  id: string;
}

export interface CreateUserRequest {
  mobile: string;
  nickname: string;
  avatarUrl: string;
}

export interface UpdateUserRequest {
  id: string;
  nickname: string;
  avatarUrl: string;
}

export interface CreateAddressRequest {
  userId: string;
  name: string;
  mobile: string;
  province: string;
  city: string;
  district: string;
  town: string;
  street: string;
  zipCode: string;
  detail: string;
  isDefault: boolean;
}

export interface GetAddressesRequest {
  userId: string;
}

export interface UpdateAddressRequest {
  id: string;
  name: string;
  mobile: string;
  province: string;
  city: string;
  district: string;
  detail: string;
  isDefault: boolean;
}

export interface DeleteAddressRequest {
  id: string;
}

export interface UserResponse {
  id: string;
  mobile: string;
  nickname: string;
  avatarUrl: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export interface AddressResponse {
  id: string;
  userId: string;
  name: string;
  mobile: string;
  province: string;
  city: string;
  district: string;
  detail: string;
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AddressListResponse {
  addresses: AddressResponse[];
}

export interface Empty {
}

export const ACCOUNT_PACKAGE_NAME = "account";

export interface AccountServiceClient {
  getUser(request: GetUserRequest, metadata?: Metadata): Observable<UserResponse>;

  createUser(request: CreateUserRequest, metadata?: Metadata): Observable<UserResponse>;

  updateUser(request: UpdateUserRequest, metadata?: Metadata): Observable<UserResponse>;

  createAddress(request: CreateAddressRequest, metadata?: Metadata): Observable<AddressResponse>;

  getAddresses(request: GetAddressesRequest, metadata?: Metadata): Observable<AddressListResponse>;

  updateAddress(request: UpdateAddressRequest, metadata?: Metadata): Observable<AddressResponse>;

  deleteAddress(request: DeleteAddressRequest, metadata?: Metadata): Observable<Empty>;
}

export interface AccountServiceController {
  getUser(
    request: GetUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  createUser(
    request: CreateUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateUser(
    request: UpdateUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  createAddress(
    request: CreateAddressRequest,
    metadata?: Metadata,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  getAddresses(
    request: GetAddressesRequest,
    metadata?: Metadata,
  ): Promise<AddressListResponse> | Observable<AddressListResponse> | AddressListResponse;

  updateAddress(
    request: UpdateAddressRequest,
    metadata?: Metadata,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  deleteAddress(request: DeleteAddressRequest, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;
}

export function AccountServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getUser",
      "createUser",
      "updateUser",
      "createAddress",
      "getAddresses",
      "updateAddress",
      "deleteAddress",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AccountService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AccountService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ACCOUNT_SERVICE_NAME = "AccountService";
