syntax = "proto3";

package account;

service AccountService {
  rpc GetUser(GetUserRequest) returns (UserResponse);
  rpc CreateUser(CreateUserRequest) returns (UserResponse);
  rpc UpdateUser(UpdateUserRequest) returns (UserResponse);
}

message GetUserRequest {
  int64 id = 1;
}

message CreateUserRequest {
  string          mobile    = 1;
  optional string nickname  = 2;
  optional string avatarUrl = 3;
}

message UpdateUserRequest {
  int64           id        = 1;
  optional string nickname  = 2;
  optional string avatarUrl = 3;
}

message UserResponse {
  int64  id        = 1;
  string mobile    = 2;
  string nickname  = 3;
  string avatarUrl = 4;
  string status    = 5;
  string createdAt = 6;
  string updatedAt = 7;
}

message Empty {}
