// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: address.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "address";

export interface CreateAddressRequest {
  userId: string;
  name: string;
  mobile: string;
  province: string;
  city: string;
  district: string;
  town?: string | undefined;
  street?: string | undefined;
  zipCode?: string | undefined;
  detail: string;
  isDefault: boolean;
}

export interface GetAddressesRequest {
  userId: string;
}

export interface UpdateAddressRequest {
  id: string;
  name: string;
  mobile: string;
  province: string;
  city: string;
  district: string;
  town?: string | undefined;
  street?: string | undefined;
  zipCode?: string | undefined;
  detail: string;
  isDefault: boolean;
}

export interface DeleteAddressRequest {
  id: string;
}

export interface AddressResponse {
  id: string;
  userId: string;
  name: string;
  mobile: string;
  province: string;
  city: string;
  district: string;
  town?: string | undefined;
  street?: string | undefined;
  zipCode?: string | undefined;
  detail: string;
  isDefault: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface AddressListResponse {
  addresses: AddressResponse[];
}

export interface Empty {
}

export const ADDRESS_PACKAGE_NAME = "address";

export interface AddressServiceClient {
  createAddress(request: CreateAddressRequest, metadata?: Metadata): Observable<AddressResponse>;

  getAddresses(request: GetAddressesRequest, metadata?: Metadata): Observable<AddressListResponse>;

  updateAddress(request: UpdateAddressRequest, metadata?: Metadata): Observable<AddressResponse>;

  deleteAddress(request: DeleteAddressRequest, metadata?: Metadata): Observable<Empty>;
}

export interface AddressServiceController {
  createAddress(
    request: CreateAddressRequest,
    metadata?: Metadata,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  getAddresses(
    request: GetAddressesRequest,
    metadata?: Metadata,
  ): Promise<AddressListResponse> | Observable<AddressListResponse> | AddressListResponse;

  updateAddress(
    request: UpdateAddressRequest,
    metadata?: Metadata,
  ): Promise<AddressResponse> | Observable<AddressResponse> | AddressResponse;

  deleteAddress(request: DeleteAddressRequest, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;
}

export function AddressServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createAddress", "getAddresses", "updateAddress", "deleteAddress"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AddressService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AddressService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ADDRESS_SERVICE_NAME = "AddressService";
