// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: category.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "category";

export interface GetCategoryRequest {
  id: number;
}

export interface ListCategoriesRequest {
  type?: string | undefined;
  parentId?: number | undefined;
  isVisible?: boolean | undefined;
  isFeatured?: boolean | undefined;
  keyword?: string | undefined;
  page: number;
  limit: number;
}

export interface CreateCategoryRequest {
  name: string;
  description?: string | undefined;
  type: string;
  parentId?: number | undefined;
  unitPrice?: number | undefined;
  priceType?: string | undefined;
  unit?: string | undefined;
  currency?: string | undefined;
  iconUrl?: string | undefined;
  sortOrder?: number | undefined;
  isVisible?: boolean | undefined;
  isFeatured?: boolean | undefined;
  slug?: string | undefined;
  basePrice?: number | undefined;
  minWeight?: number | undefined;
  maxWeight?: number | undefined;
}

export interface UpdateCategoryRequest {
  id: number;
  name?: string | undefined;
  description?: string | undefined;
  type?: string | undefined;
  parentId?: number | undefined;
  unitPrice?: number | undefined;
  priceType?: string | undefined;
  unit?: string | undefined;
  currency?: string | undefined;
  iconUrl?: string | undefined;
  sortOrder?: number | undefined;
  isVisible?: boolean | undefined;
  isFeatured?: boolean | undefined;
  slug?: string | undefined;
  basePrice?: number | undefined;
  minWeight?: number | undefined;
  maxWeight?: number | undefined;
}

export interface DeleteCategoryRequest {
  id: number;
}

export interface GetCategoryTreeRequest {
  parentId?: number | undefined;
}

export interface PricingEstimateRequest {
  items: PricingItem[];
  tenantId?: string | undefined;
  orderType?: string | undefined;
}

export interface PricingItem {
  categoryId: number;
  categoryName?: string | undefined;
  condition?: string | undefined;
  weight?: number | undefined;
  quantity?: number | undefined;
}

export interface PricingEstimateResponse {
  itemsTotal?: PriceRange | undefined;
  serviceFee: number;
  totalEstimate?: PriceRange | undefined;
  breakdown: PriceBreakdown[];
}

export interface PriceRange {
  min: number;
  max: number;
  currency: string;
}

export interface PriceBreakdown {
  itemId: number;
  itemName: string;
  quantity: number;
  weight: number;
  unitPrice: number;
  subtotal?: PriceRange | undefined;
}

export interface CategoryResponse {
  id: number;
  name: string;
  description?: string | undefined;
  type: string;
  parentId?: number | undefined;
  priceType?: string | undefined;
  unitPrice?: number | undefined;
  unit?: string | undefined;
  currency?: string | undefined;
  iconUrl?: string | undefined;
  sortOrder: number;
  isVisible: boolean;
  isFeatured: boolean;
  level: number;
  path: string;
  slug?: string | undefined;
  basePrice?: number | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

export interface ListCategoriesResponse {
  items: CategoryResponse[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface CategoryTreeResponse {
  items: CategoryResponse[];
}

export interface Empty {
}

export const CATEGORY_PACKAGE_NAME = "category";

export interface CategoryServiceClient {
  getCategory(request: GetCategoryRequest, metadata?: Metadata): Observable<CategoryResponse>;

  listCategories(request: ListCategoriesRequest, metadata?: Metadata): Observable<ListCategoriesResponse>;

  createCategory(request: CreateCategoryRequest, metadata?: Metadata): Observable<CategoryResponse>;

  updateCategory(request: UpdateCategoryRequest, metadata?: Metadata): Observable<CategoryResponse>;

  deleteCategory(request: DeleteCategoryRequest, metadata?: Metadata): Observable<Empty>;

  getCategoryTree(request: GetCategoryTreeRequest, metadata?: Metadata): Observable<CategoryTreeResponse>;

  getPricingEstimate(request: PricingEstimateRequest, metadata?: Metadata): Observable<PricingEstimateResponse>;
}

export interface CategoryServiceController {
  getCategory(
    request: GetCategoryRequest,
    metadata?: Metadata,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  listCategories(
    request: ListCategoriesRequest,
    metadata?: Metadata,
  ): Promise<ListCategoriesResponse> | Observable<ListCategoriesResponse> | ListCategoriesResponse;

  createCategory(
    request: CreateCategoryRequest,
    metadata?: Metadata,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  updateCategory(
    request: UpdateCategoryRequest,
    metadata?: Metadata,
  ): Promise<CategoryResponse> | Observable<CategoryResponse> | CategoryResponse;

  deleteCategory(request: DeleteCategoryRequest, metadata?: Metadata): Promise<Empty> | Observable<Empty> | Empty;

  getCategoryTree(
    request: GetCategoryTreeRequest,
    metadata?: Metadata,
  ): Promise<CategoryTreeResponse> | Observable<CategoryTreeResponse> | CategoryTreeResponse;

  getPricingEstimate(
    request: PricingEstimateRequest,
    metadata?: Metadata,
  ): Promise<PricingEstimateResponse> | Observable<PricingEstimateResponse> | PricingEstimateResponse;
}

export function CategoryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getCategory",
      "listCategories",
      "createCategory",
      "updateCategory",
      "deleteCategory",
      "getCategoryTree",
      "getPricingEstimate",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CategoryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CategoryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CATEGORY_SERVICE_NAME = "CategoryService";
