// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: dispatch.proto

/* eslint-disable */

export const protobufPackage = "dispatch";

export interface AssignOrderRequest {
  orderId: string;
  courierId: string;
}

export interface GetAssignmentRequest {
  id: string;
}

export interface UpdateAssignmentStatusRequest {
  id: string;
  status: string;
}

export interface AcceptAssignmentRequest {
  id: string;
}

export interface RejectAssignmentRequest {
  id: string;
}

export interface ListAssignmentsRequest {
  page: number;
  limit: number;
}

export interface AssignOrderResponse {
  success: boolean;
  orderId: string;
  courierId: string;
  assignmentId: string;
}

export interface AssignmentResponse {
  id: string;
  orderId: string;
  orderNo: string;
  courierId: string;
  taskId: string;
  status: string;
  acceptedAt?: string | undefined;
  arrivedAt?: string | undefined;
  finishedAt?: string | undefined;
  createdAt: string;
}

export interface ListAssignmentsResponse {
  items: AssignmentResponse[];
  total: number;
}
