// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: inventory.proto

/* eslint-disable */

export const protobufPackage = "inventory";

export interface GetInventoryItemRequest {
  id: string;
}

export interface ListInventoryItemsRequest {
  status?: string | undefined;
  itemType?: string | undefined;
  categoryId?: string | undefined;
  warehouseId?: string | undefined;
  page: number;
  limit: number;
}

export interface CreateInventoryItemRequest {
  warehouseId: string;
  categoryId: string;
  name: string;
  description?: string | undefined;
  unit: string;
  quantity: number;
  unitPrice: number;
  location?: string | undefined;
  itemType?: string | undefined;
  condition?: string | undefined;
  sourceOrderId?: string | undefined;
  processingStatus?: string | undefined;
}

export interface UpdateInventoryItemRequest {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  quantity?: number | undefined;
  unitPrice?: number | undefined;
  location?: string | undefined;
  status?: string | undefined;
  condition?: string | undefined;
  processingStatus?: string | undefined;
}

export interface DeleteInventoryItemRequest {
  id: string;
}

export interface CreateReservationRequest {
  itemId: string;
  quantity: number;
  orderId: string;
  expiresAt: string;
  notes?: string | undefined;
}

export interface ConfirmReservationRequest {
  reservationId: string;
}

export interface CancelReservationRequest {
  reservationId: string;
}

export interface CheckAvailabilityRequest {
  items: CheckAvailabilityItem[];
}

export interface CheckAvailabilityItem {
  categoryId: string;
  quantity: number;
}

export interface CheckAvailabilityResponse {
  available: boolean;
  items: CheckAvailabilityItemResult[];
}

export interface CheckAvailabilityItemResult {
  categoryId: string;
  available: boolean;
  availableQuantity: number;
  requestedQuantity: number;
}

export interface InventoryItemResponse {
  id: string;
  warehouseId: string;
  categoryId: string;
  name: string;
  description?: string | undefined;
  unit: string;
  quantity: number;
  reservedQty: number;
  availableQty: number;
  unitPrice: number;
  totalPrice: number;
  location?: string | undefined;
  status: string;
  itemType: string;
  condition: string;
  sourceOrderId?: string | undefined;
  processingStatus: string;
  expiryDate?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

export interface ListInventoryItemsResponse {
  items: InventoryItemResponse[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface ReservationResponse {
  id: string;
  itemId: string;
  orderId: string;
  quantity: number;
  status: string;
  expiresAt: string;
  confirmedAt?: string | undefined;
  cancelledAt?: string | undefined;
  createdAt?: string | undefined;
}

export interface InventoryStatsResponse {
  totalItems: number;
  totalValue: number;
  lowStockItems: number;
  outOfStockItems: number;
  inStockItems: number;
  expiringSoonItems: number;
  averageValue: number;
}

export interface Empty {
}
