// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: inventory.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "inventory";

export interface GetInventoryItemRequest {
  id: string;
}

export interface ListInventoryItemsRequest {
  status?: string | undefined;
  itemType?: string | undefined;
  categoryId?: string | undefined;
  warehouseId?: string | undefined;
  page: number;
  limit: number;
}

export interface CreateInventoryItemRequest {
  warehouseId: string;
  categoryId: string;
  name: string;
  description?: string | undefined;
  unit: string;
  quantity: number;
  unitPrice: number;
  location?: string | undefined;
  itemType?: string | undefined;
  condition?: string | undefined;
  sourceOrderId?: string | undefined;
  processingStatus?: string | undefined;
}

export interface UpdateInventoryItemRequest {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  quantity?: number | undefined;
  unitPrice?: number | undefined;
  location?: string | undefined;
  status?: string | undefined;
  condition?: string | undefined;
  processingStatus?: string | undefined;
}

export interface DeleteInventoryItemRequest {
  id: string;
}

export interface CreateReservationRequest {
  itemId: string;
  quantity: number;
  orderId: string;
  expiresAt: string;
  notes?: string | undefined;
}

export interface ConfirmReservationRequest {
  reservationId: string;
}

export interface CancelReservationRequest {
  reservationId: string;
}

export interface CheckAvailabilityRequest {
  items: CheckAvailabilityItem[];
}

export interface CheckAvailabilityItem {
  categoryId: string;
  quantity: number;
}

export interface CheckAvailabilityResponse {
  available: boolean;
  items: CheckAvailabilityItemResult[];
}

export interface CheckAvailabilityItemResult {
  categoryId: string;
  available: boolean;
  availableQuantity: number;
  requestedQuantity: number;
}

export interface InventoryItemResponse {
  id: string;
  warehouseId: string;
  categoryId: string;
  name: string;
  description?: string | undefined;
  unit: string;
  quantity: number;
  reservedQty: number;
  availableQty: number;
  unitPrice: number;
  totalPrice: number;
  location?: string | undefined;
  status: string;
  itemType: string;
  condition: string;
  sourceOrderId?: string | undefined;
  processingStatus: string;
  expiryDate?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
}

export interface ListInventoryItemsResponse {
  items: InventoryItemResponse[];
  total: number;
  page: number;
  limit: number;
  totalPages: number;
}

export interface ReservationResponse {
  id: string;
  itemId: string;
  orderId: string;
  quantity: number;
  status: string;
  expiresAt: string;
  confirmedAt?: string | undefined;
  cancelledAt?: string | undefined;
  createdAt?: string | undefined;
}

export interface InventoryStatsResponse {
  totalItems: number;
  totalValue: number;
  lowStockItems: number;
  outOfStockItems: number;
  inStockItems: number;
  expiringSoonItems: number;
  averageValue: number;
}

export interface Empty {
}

export const INVENTORY_PACKAGE_NAME = "inventory";

export interface InventoryServiceClient {
  getInventoryItem(request: GetInventoryItemRequest, metadata?: Metadata): Observable<InventoryItemResponse>;

  listInventoryItems(request: ListInventoryItemsRequest, metadata?: Metadata): Observable<ListInventoryItemsResponse>;

  createInventoryItem(request: CreateInventoryItemRequest, metadata?: Metadata): Observable<InventoryItemResponse>;

  updateInventoryItem(request: UpdateInventoryItemRequest, metadata?: Metadata): Observable<InventoryItemResponse>;

  deleteInventoryItem(request: DeleteInventoryItemRequest, metadata?: Metadata): Observable<Empty>;

  createReservation(request: CreateReservationRequest, metadata?: Metadata): Observable<ReservationResponse>;

  confirmReservation(request: ConfirmReservationRequest, metadata?: Metadata): Observable<ReservationResponse>;

  cancelReservation(request: CancelReservationRequest, metadata?: Metadata): Observable<ReservationResponse>;

  getInventoryStats(request: Empty, metadata?: Metadata): Observable<InventoryStatsResponse>;

  checkAvailability(request: CheckAvailabilityRequest, metadata?: Metadata): Observable<CheckAvailabilityResponse>;
}

export interface InventoryServiceController {
  getInventoryItem(
    request: GetInventoryItemRequest,
    metadata?: Metadata,
  ): Promise<InventoryItemResponse> | Observable<InventoryItemResponse> | InventoryItemResponse;

  listInventoryItems(
    request: ListInventoryItemsRequest,
    metadata?: Metadata,
  ): Promise<ListInventoryItemsResponse> | Observable<ListInventoryItemsResponse> | ListInventoryItemsResponse;

  createInventoryItem(
    request: CreateInventoryItemRequest,
    metadata?: Metadata,
  ): Promise<InventoryItemResponse> | Observable<InventoryItemResponse> | InventoryItemResponse;

  updateInventoryItem(
    request: UpdateInventoryItemRequest,
    metadata?: Metadata,
  ): Promise<InventoryItemResponse> | Observable<InventoryItemResponse> | InventoryItemResponse;

  deleteInventoryItem(
    request: DeleteInventoryItemRequest,
    metadata?: Metadata,
  ): Promise<Empty> | Observable<Empty> | Empty;

  createReservation(
    request: CreateReservationRequest,
    metadata?: Metadata,
  ): Promise<ReservationResponse> | Observable<ReservationResponse> | ReservationResponse;

  confirmReservation(
    request: ConfirmReservationRequest,
    metadata?: Metadata,
  ): Promise<ReservationResponse> | Observable<ReservationResponse> | ReservationResponse;

  cancelReservation(
    request: CancelReservationRequest,
    metadata?: Metadata,
  ): Promise<ReservationResponse> | Observable<ReservationResponse> | ReservationResponse;

  getInventoryStats(
    request: Empty,
    metadata?: Metadata,
  ): Promise<InventoryStatsResponse> | Observable<InventoryStatsResponse> | InventoryStatsResponse;

  checkAvailability(
    request: CheckAvailabilityRequest,
    metadata?: Metadata,
  ): Promise<CheckAvailabilityResponse> | Observable<CheckAvailabilityResponse> | CheckAvailabilityResponse;
}

export function InventoryServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "getInventoryItem",
      "listInventoryItems",
      "createInventoryItem",
      "updateInventoryItem",
      "deleteInventoryItem",
      "createReservation",
      "confirmReservation",
      "cancelReservation",
      "getInventoryStats",
      "checkAvailability",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("InventoryService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("InventoryService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const INVENTORY_SERVICE_NAME = "InventoryService";
