// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: notification.proto

/* eslint-disable */

export const protobufPackage = "notification";

export interface Recipient {
  userId: string;
  phoneNumber: string;
  email: string;
}

export interface NotificationContent {
  title: string;
  body: string;
}

export interface SendNotificationRequest {
  /** SMS/EMAIL/PUSH/IN_APP/WEBHOOK */
  type: string;
  recipient?: Recipient | undefined;
  content?: NotificationContent | undefined;
}

export interface SendNotificationResponse {
  id: string;
  success: boolean;
}

export interface SendBatchRequest {
  type: string;
  notifications: SendNotificationRequest[];
}

export interface SendBatchResponse {
  successCount: number;
  failedCount: number;
}

export interface CreateTemplateRequest {
  name: string;
  type: string;
  subject: string;
  content: string;
  variables: string[];
}

export interface UpdateTemplateRequest {
  id: string;
  name: string;
  subject: string;
  content: string;
  variables: string[];
}

export interface GetTemplateRequest {
  id: string;
}

export interface ListTemplatesRequest {
  type?: string | undefined;
}

export interface TemplateResponse {
  id: string;
  name: string;
  type: string;
  subject: string;
  content: string;
  variables: string[];
}

export interface ListTemplatesResponse {
  templates: TemplateResponse[];
}

export interface CallbackStatusRequest {
  id: string;
  status: string;
  messageId: string;
}

export interface CallbackStatusResponse {
  success: boolean;
}
