// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: order.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "order";

export interface CreateOrderRequest {
  userId: string;
  addressId: string;
  items: OrderItemInput[];
  remark: string;
}

export interface OrderItemInput {
  categoryId: string;
  estimatedWeight: number;
  unitPrice: number;
}

export interface CreateOrderResponse {
  success: boolean;
  orderId: string;
  message: string;
}

export interface GetOrderRequest {
  orderId: string;
}

export interface GetOrderResponse {
  order?: Order | undefined;
}

export interface Order {
  id: string;
  orderNo: string;
  userId: string;
  addressId: string;
  status: string;
  orderType: string;
  priority: number;
  expectPickupTime: string;
  actualPickupTime: string;
  expectDeliveryTime: string;
  actualDeliveryTime: string;
  estimatedAmount: string;
  settlementAmount: string;
  payAmount: string;
  channel: string;
  remark: string;
  source: string;
  createdAt: string;
  updatedAt: string;
  items: OrderItem[];
  assignments: OrderAssignment[];
}

export interface OrderItem {
  id: string;
  orderId: string;
  categoryId: string;
  estimatedWeight: number;
  actualWeight: number;
  unitPrice: number;
  amount: number;
  createdAt: string;
}

export interface OrderAssignment {
  id: string;
  orderId: string;
  courierId: string;
  status: string;
  acceptedAt: string;
  arrivedAt: string;
  finishedAt: string;
  createdAt: string;
}

export interface UpdateOrderRequest {
  orderId: string;
  status: string;
  remark: string;
}

export interface UpdateOrderResponse {
  success: boolean;
  order?: Order | undefined;
}

export interface ListOrdersRequest {
  userId: string;
  page: number;
  limit: number;
}

export interface ListOrdersResponse {
  orders: Order[];
  total: number;
  page: number;
  limit: number;
}

export interface CancelOrderRequest {
  orderId: string;
}

export interface CancelOrderResponse {
  success: boolean;
  message: string;
}

export const ORDER_PACKAGE_NAME = "order";

export interface OrderServiceClient {
  createOrder(request: CreateOrderRequest, metadata?: Metadata): Observable<CreateOrderResponse>;

  getOrder(request: GetOrderRequest, metadata?: Metadata): Observable<GetOrderResponse>;

  updateOrder(request: UpdateOrderRequest, metadata?: Metadata): Observable<UpdateOrderResponse>;

  listOrders(request: ListOrdersRequest, metadata?: Metadata): Observable<ListOrdersResponse>;

  cancelOrder(request: CancelOrderRequest, metadata?: Metadata): Observable<CancelOrderResponse>;
}

export interface OrderServiceController {
  createOrder(
    request: CreateOrderRequest,
    metadata?: Metadata,
  ): Promise<CreateOrderResponse> | Observable<CreateOrderResponse> | CreateOrderResponse;

  getOrder(
    request: GetOrderRequest,
    metadata?: Metadata,
  ): Promise<GetOrderResponse> | Observable<GetOrderResponse> | GetOrderResponse;

  updateOrder(
    request: UpdateOrderRequest,
    metadata?: Metadata,
  ): Promise<UpdateOrderResponse> | Observable<UpdateOrderResponse> | UpdateOrderResponse;

  listOrders(
    request: ListOrdersRequest,
    metadata?: Metadata,
  ): Promise<ListOrdersResponse> | Observable<ListOrdersResponse> | ListOrdersResponse;

  cancelOrder(
    request: CancelOrderRequest,
    metadata?: Metadata,
  ): Promise<CancelOrderResponse> | Observable<CancelOrderResponse> | CancelOrderResponse;
}

export function OrderServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["createOrder", "getOrder", "updateOrder", "listOrders", "cancelOrder"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("OrderService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const ORDER_SERVICE_NAME = "OrderService";
