// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: payment.proto

/* eslint-disable */

export const protobufPackage = "payment";

export interface CreatePaymentRequest {
  orderId: string;
  amount: number;
  provider: string;
}

export interface CreatePaymentResponse {
  success: boolean;
  paymentId: string;
  transactionId: string;
  message: string;
}

export interface GetPaymentRequest {
  paymentId: string;
}

export interface GetPaymentResponse {
  payment?: Payment | undefined;
}

export interface Payment {
  id: string;
  orderId: string;
  transactionId: string;
  outTradeNo: string;
  total: number;
  status: string;
  provider: string;
  notifyRaw?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface UpdatePaymentStatusRequest {
  transactionId: string;
  status: string;
}

export interface UpdatePaymentStatusResponse {
  success: boolean;
  payment?: Payment | undefined;
}

export interface CreateRefundRequest {
  paymentId: string;
  refundAmount: number;
  reason: string;
}

export interface CreateRefundResponse {
  success: boolean;
  refundId: string;
  outRefundNo: string;
  message: string;
}

export interface GetRefundRequest {
  refundId: string;
}

export interface GetRefundResponse {
  refund?: Refund | undefined;
}

export interface Refund {
  id: string;
  paymentId: string;
  outRefundNo: string;
  refundAmount: number;
  status: string;
  reason: string;
  notifyRaw?: string | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface CreatePaymentLogRequest {
  orderId: string;
  transactionId: string;
  status: string;
  amount: string;
  provider: string;
  reason?: string | undefined;
}

export interface PaymentLogResponse {
  id: string;
  orderId: string;
  transactionId: string;
  status: string;
  amount: string;
  provider: string;
  reason: string;
  createdAt: string;
  updatedAt: string;
}

export interface PaymentLogsResponse {
  logs: PaymentLogResponse[];
}

export interface GetPaymentLogsByOrderIdRequest {
  orderId: string;
}

export interface GetPaymentLogByTransactionIdRequest {
  transactionId: string;
}

export interface IsTransactionProcessedRequest {
  transactionId: string;
}

export interface IsTransactionProcessedResponse {
  processed: boolean;
}

export interface GetPaymentStatsRequest {
  startDate: string;
  endDate: string;
}

export interface PaymentStatsResponse {
  total: number;
  success: number;
  failed: number;
  closed: number;
  totalAmount: string;
}
