// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: queue.proto

/* eslint-disable */

export const protobufPackage = "queue";

export interface PublishTaskRequest {
  queue: string;
  payload: string;
  priority: number;
  delayMs: string;
}

export interface PublishTaskResponse {
  taskId: string;
}

export interface AckRequest {
  taskId: string;
}

export interface AckResponse {
  success: boolean;
}

export interface NackRequest {
  taskId: string;
  reason: string;
}

export interface NackResponse {
  success: boolean;
}

export interface ConsumeRequest {
  queue: string;
  maxInFlight: number;
}

export interface TaskMessage {
  taskId: string;
  payload: string;
  priority: number;
}
