// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: user.proto

/* eslint-disable */
import type { Metadata } from "@grpc/grpc-js";
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "user";

export interface FindOneRequest {
  id: string;
}

export interface FindByMobileRequest {
  mobile: string;
}

export interface FindByIdentityRequest {
  provider: string;
  openid: string;
}

export interface CreateUserRequest {
  mobile?: string | undefined;
  nickname?: string | undefined;
  avatarUrl?: string | undefined;
}

export interface UpdateUserRequest {
  id: string;
  nickname?: string | undefined;
  avatarUrl?: string | undefined;
  mobile?: string | undefined;
}

export interface UserResponse {
  id: string;
  email?: string | undefined;
  mobile?: string | undefined;
  nickname?: string | undefined;
  avatarUrl?: string | undefined;
  role: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}

export const USER_PACKAGE_NAME = "user";

export interface UserServiceClient {
  findOne(request: FindOneRequest, metadata?: Metadata): Observable<UserResponse>;

  findByMobile(request: FindByMobileRequest, metadata?: Metadata): Observable<UserResponse>;

  findByIdentity(request: FindByIdentityRequest, metadata?: Metadata): Observable<UserResponse>;

  createUser(request: CreateUserRequest, metadata?: Metadata): Observable<UserResponse>;

  updateUser(request: UpdateUserRequest, metadata?: Metadata): Observable<UserResponse>;
}

export interface UserServiceController {
  findOne(
    request: FindOneRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  findByMobile(
    request: FindByMobileRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  findByIdentity(
    request: FindByIdentityRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  createUser(
    request: CreateUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;

  updateUser(
    request: UpdateUserRequest,
    metadata?: Metadata,
  ): Promise<UserResponse> | Observable<UserResponse> | UserResponse;
}

export function UserServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["findOne", "findByMobile", "findByIdentity", "createUser", "updateUser"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("UserService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const USER_SERVICE_NAME = "UserService";
