syntax = "proto3";

package user;

service UserService {
  rpc FindOne (FindOneRequest) returns (UserResponse);
  rpc FindByMobile (FindByMobileRequest) returns (UserResponse);
  rpc FindByIdentity (FindByIdentityRequest) returns (UserResponse);
  rpc CreateUser (CreateUserRequest) returns (UserResponse);
  rpc UpdateUser (UpdateUserRequest) returns (UserResponse);
}

message FindOneRequest {
  int64 id = 1;
}

message FindByMobileRequest {
  string mobile = 1;
}

message FindByIdentityRequest {
  string provider = 1;
  string openid = 2;
}

message CreateUserRequest {
  optional string mobile = 1;
  optional string nickname = 2;
  optional string avatarUrl = 3;
}

message UpdateUserRequest {
  int64 id = 1;
  optional string nickname = 2;
  optional string avatarUrl = 3;
  optional string mobile = 4;
}

message UserResponse {
  int64 id = 1;
  optional string email = 2;
  optional string mobile = 3;
  optional string nickname = 4;
  optional string avatarUrl = 5;
  string role = 6;
  string status = 7;
  string createdAt = 8;
  string updatedAt = 9;
}
