// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.6
//   protoc               v5.29.3
// source: user.proto

/* eslint-disable */

export const protobufPackage = "user";

export interface FindOneRequest {
  id: string;
}

export interface FindByMobileRequest {
  mobile: string;
}

export interface FindByIdentityRequest {
  provider: string;
  openid: string;
}

export interface CreateUserRequest {
  mobile?: string | undefined;
  nickname?: string | undefined;
  avatarUrl?: string | undefined;
}

export interface UpdateUserRequest {
  id: string;
  nickname?: string | undefined;
  avatarUrl?: string | undefined;
  mobile?: string | undefined;
}

export interface UserResponse {
  id: string;
  email?: string | undefined;
  mobile?: string | undefined;
  nickname?: string | undefined;
  avatarUrl?: string | undefined;
  role: string;
  status: string;
  createdAt: string;
  updatedAt: string;
}
