import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Sidebar from './components/Sidebar';
import Header from './components/Header';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "回收后台管理",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <div style={{ minHeight: '100vh', display: 'flex' }}>
            <Sidebar />
            <div style={{ flex: 1, marginLeft: 200 }}>
              <Header />
              <div style={{ margin: '80px 16px 0', overflow: 'initial' }}>
                <div style={{ padding: 24, background: '#fff', minHeight: 360 }}>
                  {children}
                </div>
              </div>
            </div>
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}