import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import Sidebar from '@/components/Sidebar';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: '回收后台管理',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AntdRegistry>
          <div className={styles.container}>
            <Sidebar />
            <div className={styles.mainContent}>
              <Header />
              <div className={styles.contentWrapper}>
                <div className={styles.pageContent}>{children}</div>
              </div>
            </div>
          </div>
        </AntdRegistry>
      </body>
    </html>
  );
}
