DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_type WHERE typname = 'OrderStatus'
  ) THEN
    CREATE TYPE "OrderStatus" AS ENUM (
      'PENDING',
      'PENDING_PICKUP',
      'PICKED_UP',
      'IN_TRANSIT',
      'PENDING_RECEIPT',
      'INSPECTING',
      'INSPECTED',
      'INSPECTION_EXCEPTION',
      'MANUAL_PROCESSING',
      'PENDING_INBOUND',
      'INBOUNDED',
      'PENDING_SETTLEMENT',
      'COMPLETED',
      'REFUNDED',
      'CANCELLED'
    );
  END IF;
END $$;

UPDATE "orders"
SET "status" = CASE
  WHEN "status" IS NULL THEN 'PENDING'
  WHEN UPPER("status") IN (
    'PENDING',
    'PENDING_PICKUP',
    'PICKED_UP',
    'IN_TRANSIT',
    'PENDING_RECEIPT',
    'INSPECTING',
    'INSPECTED',
    'INSPECTION_EXCEPTION',
    'MANUAL_PROCESSING',
    'PENDING_INBOUND',
    'INBOUNDED',
    'PENDING_SETTLEMENT',
    'COMPLETED',
    'REFUNDED',
    'CANCELLED'
  ) THEN UPPER("status")
  ELSE 'PENDING'
END;

ALTER TABLE "orders"
ALTER COLUMN "status" DROP DEFAULT;

ALTER TABLE "orders"
ALTER COLUMN "status" TYPE "OrderStatus" USING "status"::"OrderStatus";

ALTER TABLE "orders"
ALTER COLUMN "status" SET DEFAULT 'PENDING';
